version: '3'

services:
  neo4j:
    image: neo4j:5.3.0
    volumes:
      - "./data:/data"
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
